In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import math
from patsy import dmatrices


import statsmodels.discrete.discrete_model as sm
import statsmodels.formula.api as smf
from statsmodels.graphics.regressionplots import *
from sklearn import datasets, linear_model
from sklearn.metrics import confusion_matrix

In [3]:
Smarket = pd.read_csv('/Users/shilpa/Documents/blog/Sharing_ISL_python/data/Smarket.csv', header=0)
Smarket.shape

NameError: name 'pd' is not defined

In [9]:
Smarket.corr()

Year      Lag1      Lag2      Lag3      Lag4      Lag5    Volume  \
Year    1.000000  0.029700  0.030596  0.033195  0.035689  0.029788  0.539006   
Lag1    0.029700  1.000000 -0.026294 -0.010803 -0.002986 -0.005675  0.040910   
Lag2    0.030596 -0.026294  1.000000 -0.025897 -0.010854 -0.003558 -0.043383   
Lag3    0.033195 -0.010803 -0.025897  1.000000 -0.024051 -0.018808 -0.041824   
Lag4    0.035689 -0.002986 -0.010854 -0.024051  1.000000 -0.027084 -0.048414   
Lag5    0.029788 -0.005675 -0.003558 -0.018808 -0.027084  1.000000 -0.022002   
Volume  0.539006  0.040910 -0.043383 -0.041824 -0.048414 -0.022002  1.000000   
Today   0.030095 -0.026155 -0.010250 -0.002448 -0.006900 -0.034860  0.014592   

           Today  
Year    0.030095  
Lag1   -0.026155  
Lag2   -0.010250  
Lag3   -0.002448  
Lag4   -0.006900  
Lag5   -0.034860  
Volume  0.014592  
Today   1.000000

In [13]:
y, X = dmatrices('Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume', Smarket, return_type = 'dataframe')
print(X)

      Intercept   Lag1   Lag2   Lag3   Lag4   Lag5   Volume
0           1.0  0.381 -0.192 -2.624 -1.055  5.010  1.19130
1           1.0  0.959  0.381 -0.192 -2.624 -1.055  1.29650
2           1.0  1.032  0.959  0.381 -0.192 -2.624  1.41120
3           1.0 -0.623  1.032  0.959  0.381 -0.192  1.27600
4           1.0  0.614 -0.623  1.032  0.959  0.381  1.20570
...         ...    ...    ...    ...    ...    ...      ...
1245        1.0  0.422  0.252 -0.024 -0.584 -0.285  1.88850
1246        1.0  0.043  0.422  0.252 -0.024 -0.584  1.28581
1247        1.0 -0.955  0.043  0.422  0.252 -0.024  1.54047
1248        1.0  0.130 -0.955  0.043  0.422  0.252  1.42236
1249        1.0 -0.298  0.130 -0.955  0.043  0.422  1.38254

[1250 rows x 7 columns]


In [26]:
logit = sm.Logit(y.iloc[:,1], X).fit()
logit.summary()

Optimization terminated successfully.
         Current function value: 0.691034
         Iterations 4


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:          Direction[Up]   No. Observations:                 1250
Model:                          Logit   Df Residuals:                     1243
Method:                           MLE   Df Model:                            6
Date:                Wed, 02 Sep 2020   Pseudo R-squ.:                0.002074
Time:                        17:44:04   Log-Likelihood:                -863.79
converged:                       True   LL-Null:                       -865.59
Covariance Type:            nonrobust   LLR p-value:                    0.7319
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.1260      0.241     -0.523      0.601      -0.598       0.346
Lag1          -0.0731      0.050     -1.457      0.145      -0.171       0.025
Lag2          -0.0423      0.050     -0.845      0.398      -0.140       0.056
Lag3           0.0111      0.050      0.222      0.824      -0.087       0.109
Lag4           0.0094      0.050      0.187      0.851      -0.089       0.107
Lag5           0.0103      0.050      0.208      0.835      -0.087       0.107
Volume         0.1354      0.158      0.855      0.392      -0.175       0.446
==============================================================================
"""

In [33]:
logit.predict() # To extract the probability of the market going up

array([0.50708413, 0.48146788, 0.48113883, ..., 0.5392683 , 0.52611829,
       0.51791656])

In [31]:
predict_label = pd.DataFrame(np.zeros(shape=(1250,1)), columns = ['label'])

In [34]:
predict_label.iloc[logit.predict()>0.5] = 1

In [57]:
logit.predict()

array([0.49850615, 0.4893137 , 0.48497911, 0.5098788 , 0.51457371,
       0.49820443, 0.48353071, 0.49843449, 0.52041065, 0.4953121 ,
       0.48888171, 0.5175062 , 0.52671407, 0.50833901, 0.49565848,
       0.51118446, 0.51687627, 0.53408848, 0.53279476, 0.51326559,
       0.52449532, 0.53578132, 0.53952859, 0.51453505, 0.5122034 ,
       0.52783894, 0.5075255 , 0.5245241 , 0.56234338, 0.55553326,
       0.52489434, 0.5176419 , 0.49611599, 0.50640833, 0.54269931,
       0.52714378, 0.51103898, 0.51804768, 0.49649862, 0.49476256,
       0.50831437, 0.54918052, 0.59802822, 0.53278889, 0.51320455,
       0.53112638, 0.5250673 , 0.50898873, 0.52443121, 0.55963004,
       0.52427421, 0.47686769, 0.47629123, 0.46692658, 0.51851374,
       0.55031637, 0.49980766, 0.50839513, 0.57164283, 0.54949763,
       0.44311419, 0.48328925, 0.53973728, 0.46640821, 0.47583988,
       0.5060503 , 0.51144099, 0.50484566, 0.43012024, 0.44305572,
       0.51509396, 0.55564462, 0.54234562, 0.49976083, 0.48039

In [39]:
confusion_matrix(y.iloc[:,1], predict_label.iloc[:,0])

array([[145, 457],
       [141, 507]])

In [40]:
np.mean(y.iloc[:,1] == predict_label.iloc[:,0]) # to get accuracy

0.5216

In [42]:
Smarket_2005 = Smarket.query('Year >= 2005')
Smarket_train = Smarket.query('Year < 2005')
y_train, X_train = dmatrices('Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume', Smarket_train, return_type = 'dataframe')
y_test, X_test = dmatrices('Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume', Smarket_2005, return_type = 'dataframe')

In [105]:
y_test

Direction[Down]  Direction[Up]
998               1.0            0.0
999               1.0            0.0
1000              1.0            0.0
1001              0.0            1.0
1002              1.0            0.0
...               ...            ...
1245              0.0            1.0
1246              1.0            0.0
1247              0.0            1.0
1248              1.0            0.0
1249              1.0            0.0

[252 rows x 2 columns]

In [44]:
logit = sm.Logit(y_train.iloc[:,1],X_train).fit()

Optimization terminated successfully.
         Current function value: 0.691936
         Iterations 4


In [79]:
pred_lable

label
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
..     ...
247    0.0
248    0.0
249    0.0
250    0.0
251    0.0

[252 rows x 1 columns]

In [81]:
pred=logit.predict(X_test)
pred=np.asarray(pred)
pred_lable=pd.DataFrame(np.zeros(shape=(X_test.shape[0],1)), columns = ['label'])
pred_lable.iloc[pred>0.5]=1
confusion_matrix(y_test.iloc[:,1], pred_lable.iloc[:,0])

array([[77, 34],
       [97, 44]])

In [84]:
np.mean(y_test.iloc[:,1].reset_index(drop=True)==pred_lable.iloc[:,0].reset_index(drop=True)) # to get accuracy

0.4801587301587302

## 4.6.3 Linear Discriminant Analysis

In [91]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
LDA?

In [99]:
skl_lda = LDA(n_components=2).fit(X_train.iloc[:,1:3],y_train.iloc[:,1])
X_labels=skl_lda.predict(X_train.iloc[:,1:3])
X_prob=skl_lda.predict_proba(X_train.ix[:,1:3])

/Users/shilpa/Library/Python/3.7/lib/python/site-packages/sklearn/discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(2, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
/Users/shilpa/Library/Python/3.7/lib/python/site-packages/sklearn/discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)


array([[0.49509888, 0.50490112],
       [0.50946124, 0.49053876],
       [0.51687563, 0.48312437],
       ...,
       [0.49707844, 0.50292156],
       [0.49977625, 0.50022375],
       [0.49198053, 0.50801947]])

In [107]:
X_test_labels=skl_lda.predict(X_test.iloc[:,1:3])
X_test_prob = skl_lda.predict_proba(X_test.iloc[:,1:3]) 
X_test_labels

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 0., 0., 0.

In [108]:
np.mean(y_test.iloc[:,1]==X_test_labels)

0.5595238095238095

In [113]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
QDA?

In [116]:
sk_qda=QDA(store_covariance=True).fit(X_train.iloc[:,1:3],y_train.iloc[:,1])
X_labels = sk_qda.predict(X_train.ix[:,1:3]) #gives you the predicted label for each sample
X_prob = sk_qda.predict_proba(X_train.ix[:,1:3]) #the probability of each sample to belong to each class

X_test_labels=sk_qda.predict(X_test.ix[:,1:3])
X_test_prob = sk_qda.predict_proba(X_test.ix[:,1:3]) 

print(np.mean(y_test.ix[:,1]==X_test_labels))

0.5992063492063492


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  
/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel pa

In [119]:
print(sk_qda.means_)
print(sk_qda.covariance_)

[[ 0.04279022  0.03389409]
 [-0.03954635 -0.03132544]]
[array([[ 1.50662277, -0.03924806],
       [-0.03924806,  1.53559498]]), array([[ 1.51700576, -0.02787349],
       [-0.02787349,  1.49026815]])]


In [121]:
from sklearn.neighbors import KNeighborsClassifier as KNN
KNN?

In [129]:
nhb_knn=KNN(n_neighbors=4).fit(X_train.iloc[:,1:3],y_train.iloc[:,1])
X_test_labels=nhb_knn.predict(X_test.ix[:,1:3])
X_test_prob = nhb_knn.predict_proba(X_test.ix[:,1:3]) 
print(np.mean(y_test.ix[:,1]==X_test_labels))
dir(nhb_knn) # use dir command to check what KNN offers
nhb_knn

0.5158730158730159


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  
/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel pa

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [130]:
Caravan = pd.read_csv('/Users/shilpa/Documents/blog/Sharing_ISL_python/data/Caravan.csv', header=0)

In [132]:
Caravan.shape
Caravan.head()
Caravan.describe()

MOSTYPE  MAANTHUI  MGEMOMV  MGEMLEEF  MOSHOOFD  MGODRK  MGODPR  MGODOV  \
0       33         1        3         2         8       0       5       1   
1       37         1        2         2         8       1       4       1   
2       37         1        2         2         8       0       4       2   
3        9         1        3         3         3       2       3       2   
4       40         1        4         2        10       1       4       1   

   MGODGE  MRELGE  ...  APERSONG  AGEZONG  AWAOREG  ABRAND  AZEILPL  APLEZIER  \
0       3       7  ...         0        0        0       1        0         0   
1       4       6  ...         0        0        0       1        0         0   
2       4       3  ...         0        0        0       1        0         0   
3       4       5  ...         0        0        0       1        0         0   
4       4       7  ...         0        0        0       1        0         0   

   AFIETS  AINBOED  ABYSTAND  Purchase  
0       0        0         0        No  
1       0        0         0        No  
2       0        0         0        No  
3       0        0         0        No  
4       0        0         0        No  

[5 rows x 86 columns]

In [133]:
predict_label = pd.DataFrame(np.zeros(shape=(Caravan.shape[0],1)), columns = ['label'])
predict_label.ix[Caravan['Purchase'] == 'Yes'] = 1
Caravan_drop = Caravan.drop(labels='Purchase', axis=1)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


In [145]:
from sklearn import preprocessing
train_size = 1000
train_index = range(0, train_size)
X_validate = Caravan_drop.ix[train_index, ]
Y_validate = predict_label.ix[train_index, ]
X_train = Caravan_drop.ix[train_size:, ]
Y_train = predict_label.ix[train_size:, ]


X_train_scaled = preprocessing.scale(X_train)
X_validate_scaled = preprocessing.scale(X_validate)

[[ 0.66349911 -0.25791484  0.41065077 ... -0.13262641 -0.08396038
  -0.12427976]
 [ 0.97142305 -0.25791484 -0.86071385 ... -0.13262641 -0.08396038
  -0.12427976]
 [ 0.97142305 -0.25791484 -0.86071385 ... -0.13262641 -0.08396038
  -0.12427976]
 ...
 [ 0.66349911 -0.25791484  0.41065077 ... -0.13262641 -0.08396038
  -0.12427976]
 [-1.64593044 -0.25791484 -0.86071385 ... -0.13262641 -0.08396038
  -0.12427976]
 [ 0.66349911 -0.25791484 -0.86071385 ... -0.13262641 -0.08396038
  -0.12427976]] StandardScaler(copy=True, with_mean=True, with_std=True)


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  
/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py:

In [146]:
neigh = KNN(n_neighbors= 1) # use n_neighbors to change the # of tune the performance of KNN
KNN_fit = neigh.fit(X_train_scaled, Y_train.ix[:,0]) #learning the projection matrix
X_validate_labels=KNN_fit.predict(X_validate_scaled)
X_validate_prob = KNN_fit.predict_proba(X_validate_scaled) 

print(np.mean(Y_validate.ix[:,0]==X_validate_labels))
print(confusion_matrix(Y_validate.ix[:,0], X_validate_labels))

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


0.883
[[874  67]
 [ 50   9]]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  import sys
